version: '3.7'
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src
    ports:
      - "8008:8008"
    environment:
      - PORT=8008      
    entrypoint: /start-reload.sh
